#!/bin/bash
set -e

chown -R mysql:mysql /var/lib/mysql
mysql_install_db --user mysql > /dev/null

ROOT_PASSWORD=${ROOT_PASSWORD:-"pwd01"}
MY_USER=${MY_USER:-"ubuntu"}
MY_PASSWORD=${MY_PASSWORD:-"pwd01"}
MYSQL_DATABASE=${MYSQL_DATABASE:-"default_db"}


# Setup MySQL
tfile=`mktemp`
if [[ ! -f "$tfile" ]]; then
    return 1
fi

cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
UPDATE user SET password=PASSWORD("$ROOT_PASSWORD") WHERE user='root';
EOF

if [[ $MYSQL_DATABASE != "" ]]; then
    echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile
    if [[ $MY_USER != "" ]]; then
        echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* to '$MY_USER'@'%' IDENTIFIED BY '$MY_PASSWORD';" >> $tfile
    fi

    echo "CREATE DATABASE IF NOT EXISTS \`phpmyadmin\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile
    if [[ $MY_USER != "" ]]; then
        echo "GRANT ALL ON \`phpmyadmin\`.* to '$MY_USER'@'%' IDENTIFIED BY '$MY_PASSWORD';" >> $tfile
    fi
    echo "USE \`phpmyadmin\`;" >> $tfile
    echo "CREATE TABLE IF NOT EXISTS \`pma_recent\` (\`username\` int(11) NOT NULL, \`tables\` int(11) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;" >> $tfile
    echo "CREATE TABLE IF NOT EXISTS \`pma_table_uiprefs\` (\`username\` int(11) NOT NULL, \`prefs\` int(11) NOT NULL, \`db_name\` int(11) NOT NULL, \`table_name\` int(11) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;" >> $tfile
fi

/usr/sbin/mysqld --bootstrap --verbose=0 < $tfile
rm -f $tfile

# Create a user
echo "User: $MY_USER Pass: $MY_PASSWORD"
useradd --create-home --shell /bin/bash --user-group --groups adm,sudo $MY_USER
echo "$MY_USER:$MY_PASSWORD" | chpasswd

